### ISSUE TITLE
brew error

### ISSUE THREAD

**Issue by lixianzhao** [akash-network/homebrew-tap#3]
$  brew tap ovrclk/tap

Invalid formula: /usr/local/Homebrew/Library/Taps/ovrclk/homebrew-tap/akash-edge.rb
akash-edge: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the ovrclk/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/ovrclk/homebrew-tap/akash-edge.rb:9

**Comment by mweichert** [comment]
I'm getting this as well. I see you closed this issue @lixianzhao - does that mean that you found a solution?
